const MaleWearProducts = [
    { title: "Men Suit Solid Suit", image: "../../src/assets/img/suit.jpg", price: 1000, category: "Men's Wear", subcategory: "Suits", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "A stylish solid suit." },
    { title: "Men 2 Piece Checkered Suit", image: "../../src/assets/img/img-2.jpg", price: 700, category: "Men's Wear", subcategory: "Suits", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "A checkered two-piece suit." },
    { title: "Wedding Suit", image: "../../src/assets/img/img-3.jpg", price: 900, category: "Men's Wear", subcategory: "Suits", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Perfect wedding attire." },
    { title: "Party Wear Suit", image: "../../src/assets/img/img-4.jpg", price: 1500, category: "Men's Wear", subcategory: "Suits", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Trendy party suit." },
    { title: "Action Men Tan Solid Leather Formal Shoes", image: "../../src/assets/img/foot-1.jpg", price: 1000, category: "Footwear", subcategory: "Formal Shoes", sizes: ["6", "7", "8", "9", "10", "11"], description: "Elegant tan formal shoes.", location: "Kolkata", status: "Active" },
    { title: "FAUSTO Men Navy Blue Textured Derby Shoes", image: "../../src/assets/img/foot-2.jpg", price: 750, category: "Footwear", subcategory: "Formal Shoes", sizes: ["6", "7", "8", "9", "10", "11"], description: "Stylish navy blue shoes." },
    { title: "EZOK Men Tan Solid Leather Derby Shoes", image: "../../src/assets/img/foot-3.jpg", price: 900, category: "Footwear", subcategory: "Formal Shoes", sizes: ["6", "7", "8", "9", "10", "11"], description: "Classic tan leather derby shoes." },
    { title: "FAUSTO Men Tan Slip-On Formal Shoes", image: "../../src/assets/img/foot-4.jpg", price: 1000, category: "Footwear", subcategory: "Formal Shoes", sizes: ["6", "7", "8", "9", "10", "11"], description: "Comfortable slip-on shoes." },
    { title: "Fentacia Men Black Solid Leather Slip-On Shoes", image: "../../src/assets/img/foot-5.jpg", price: 1250, category: "Footwear", subcategory: "Formal Shoes", sizes: ["6", "7", "8", "9", "10", "11"], description: "Premium black slip-on shoes." },
    { title: "Fentacia Men Brown Solid Leather Slip-On Shoes", image: "../../src/assets/img/foot-6.jpg", price: 1350, category: "Footwear", subcategory: "Formal Shoes", sizes: ["6", "7", "8", "9", "10", "11"], description: "Stylish brown slip-on shoes." },
    { title: "Liberty Men Tan Solid Leather Derby Shoes", image: "../../src/assets/img/foot-7.jpg", price: 1150, category: "Footwear", subcategory: "Formal Shoes", sizes: ["6", "7", "8", "9", "10", "11"], description: "Classic Liberty derby shoes." },
    { title: "One8 Men Tan Solid Leather Slip-On Shoes", image: "../../src/assets/img/foot-8.jpg", price: 800, category: "Footwear", subcategory: "Formal Shoes", sizes: ["6", "7", "8", "9", "10", "11"], description: "Trendy One8 slip-on shoes." },
];

const FemaleWearProducts = [
    { title: "Female Wedding Set", image: "../../src/assets/img/Female/fe1.jpg", price: 1000, category: "Women's Wear", subcategory: "Wedding Dress", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Elegant wedding set for special occasions." },
    { title: "Female 2 Piece", image: "../../src/assets/img/Female/fe2.jpg", price: 750, category: "Women's Wear", subcategory: "Ethnic Wear", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Trendy two-piece outfit for any event." },
    { title: "Party Wear", image: "../../src/assets/img/Female/fe3.jpg", price: 900, category: "Women's Wear", subcategory: "Party Dress", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Perfect dress for evening parties." },
    { title: "Black Mini Dress", image: "../../src/assets/img/Female/fe4.jpg", price: 1500, category: "Women's Wear", subcategory: "Western Wear", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Stylish black mini dress for modern looks." },
    { title: "Indian Full Set", image: "../../src/assets/img/Female/fe5.jpg", price: 1500, category: "Women's Wear", subcategory: "Traditional Wear", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Elegant full-set Indian attire." },
    { title: "Western Blue Dress", image: "../../src/assets/img/Female/fe6.jpg", price: 1800, category: "Women's Wear", subcategory: "Western Wear", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Classy blue western outfit." },
    { title: "Party Wear", image: "../../src/assets/img/Female/fe7.jpg", price: 1200, category: "Women's Wear", subcategory: "Party Dress", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Trendy dress for special occasions." },
    { title: "Party Wear", image: "../../src/assets/img/Female/fe8.jpg", price: 1200, category: "Women's Wear", subcategory: "Party Dress", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Elegant party wear dress." },
    { title: "Party Wear", image: "../../src/assets/img/Female/fe9.jpg", price: 1200, category: "Women's Wear", subcategory: "Party Dress", sizes: ["XS", "S", "M", "L", "XL", "XXL"], description: "Graceful party dress for any celebration." },
    { title: "2-Inches Kitten Heel", image: "../../src/assets/img/Female/ft1.jpg", price: 1000, category: "Footwear", subcategory: "Heels", sizes: ["6", "7", "8", "9", "10", "11"], description: "Chic kitten heels for casual elegance." },
    { title: "Sandals Party High Heel 11 cm", image: "../../src/assets/img/Female/ft2.jpg", price: 750, category: "Footwear", subcategory: "Heels", sizes: ["6", "7", "8", "9", "10", "11"], description: "Fashionable high heels for parties." },
    { title: "Jimmy Choo Wedding Bridal Shoes", image: "../../src/assets/img/Female/ft3.jpg", price: 900, category: "Footwear", subcategory: "Bridal Shoes", sizes: ["6", "7", "8", "9", "10", "11"], description: "Elegant bridal shoes for weddings." },
    { title: "Women's Party Shoes", image: "../../src/assets/img/Female/ft4.jpg", price: 1000, category: "Footwear", subcategory: "Heels", sizes: ["6", "7", "8", "9", "10", "11"], description: "Stylish footwear for parties." },
    { title: "Wedding Shoes", image: "../../src/assets/img/Female/ft5.jpg", price: 1500, category: "Footwear", subcategory: "Bridal Shoes", sizes: ["6", "7", "8", "9", "10", "11"], description: "Classic and stylish wedding shoes." },
    { title: "Bridal Shoes", image: "../../src/assets/img/Female/ft6.jpg", price: 1600, category: "Footwear", subcategory: "Bridal Shoes", sizes: ["6", "7", "8", "9", "10", "11"], description: "Luxurious bridal footwear for a grand wedding." },
    { title: "Woman Party Fashion Rivets Shoes", image: "../../src/assets/img/Female/ft7.jpg", price: 1400, category: "Footwear", subcategory: "Heels", sizes: ["6", "7", "8", "9", "10", "11"], description: "Trendy rivet-styled party shoes." },
    { title: "Pretty Footwear for Indian Dresses", image: "../../src/assets/img/Female/ft8.jpg", price: 1000, category: "Footwear", subcategory: "Traditional Footwear", sizes: ["6", "7", "8", "9", "10", "11"], description: "Elegant footwear to pair with traditional attire." },
    { title: "Thin High Heels Sandals", image: "../../src/assets/img/Female/ft9.jpg", price: 1000, category: "Footwear", subcategory: "Heels", sizes: ["6", "7", "8", "9", "10", "11"], description: "Sleek and stylish high-heel sandals." },
];

export default { MaleData: MaleWearProducts, FemaleData: FemaleWearProducts };
